import Navigator from '@/components/Navigator'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Routes } from '@/models/routes.model'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App Ceti',
  description: 'Generated by create next app ceti',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ padding:'10px' }}>
        <Navigator pathNames={[Routes.HOME, Routes.CHARACTERES]}></Navigator>
        {children}
        </body>
    </html>
  )
}
